### ISSUE TITLE
Route / to /status

### ISSUE THREAD

**Issue by wpears** [cfpb/grasshopper-parser#14]
Seems like anytime you'd hit the parser's root path (say **localhost:5000** or **localhost:5000/**), you'd actually just be checking its status, so why not route it the same as a request to **/status**. Seems like a nice little redundancy, and more useful returning an empty 200 (or a 404, which is the current state of affairs).

**Comment by hkeeler** [comment]
Agreed.  We definitely need _something_ there.  I was thinking of an index-style representation describing the available endpoints...but then I decided that was more work than it was worth at this point.  Routing/redirecting to `/status` seems like a good option for now.

**Comment by wpears** [comment]
Heh, how very HATEOAS of you. Honestly a machine-readable index of the available endpoints/options would be useful; probably more useful that just mapping / to /status.

But as you say, it may be more work than it's worth for now. If it every strikes your fancy, I'd say go for it.

**Comment by hkeeler** [comment]
This was completed under #24.  I still like the idea of a developer friendly HATEOAS-y index resource at `/`, but not a priority...yet. :)  Closing this out.
